### ISSUE TITLE
Inspecting Campaing

### ISSUE THREAD

**Issue by glanzel** [neon-jungle/wagtail-birdsong#7]
When inspecting a already send Campaign.
Eventhough the email is sucessfully send 
und Recipients is is still written Success = False  

```
Contact | Succeess | Sent date -- | -- | --
username@domain.com | False | Jan. 20, 2021, 1:37 p.m.

```

**Comment by glanzel** [comment]
Seems to me that success is never set in the process of sending and instead only the default value is written to the Database.
`class Receipt(models.Model):
    success = models.BooleanField(default=False)
`

**Comment by glanzel** [comment]
in this case if you just set
`models.BooleanField(default=True) `
it shows the correct value.
And later you could add additional checks if wanted.

**Comment by MaximMalyavkoSolbeg** [comment]
Sorry, I would like to clarify.

I didn't find appropriate migration (https://github.com/neon-jungle/wagtail-birdsong/tree/master/birdsong/migrations) for this changing: 
- class Receipt(models.Model): success = models.BooleanField(default=False)
+ class Receipt(models.Model): success = models.BooleanField(default=True)

Was it intentional?

I'll try to explain why it is interesting for me.
1. I create my custom contact model and inherit from birdsong.models.Contact
2. I run 'manage.py makemigrations' and receive two new migration:
    - in packet 'birdsong' in my venv '0005_auto_... .py'. The migration realizes changing above.
    - in my app '0001_initial.py'. In this migration  I see dependencies
    `    dependencies = [
        ('birdsong', '0005_auto_...'), ...
    ]`

As result, when I transfer the changes to container in production via CI/CD I can't migrate, because of course there are not migration '0005_auto_... .py' in packet 'birdsong' on production.

As workaround I can change dependencies in my migration file:
from ('birdsong', '0005_auto_...') to ('birdsong', '0004_campaign_status').
But I'm worried that this may cause issues with wagtail-birdsong version in the future.

Thank you.
